sudo: required
services:
  - docker

before_install:
  - docker build -t rajahuja1985/docker-react -f Dockerfile.dev .

script:
  - docker run -it rajahuja1985/docker-react npm run test -- --coverage
